<?php

namespace App;

use App\Notifications\ResetPasswordNotification;
use Cartalyst\Sentinel\Users\EloquentUser;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends EloquentUser
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'permissions'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
    ];

    /**
     * Добавим токен к массиву данных при создании нового пользователя.
     */
    /*public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function($user){
            $user->token = str_random(30);
        });
    }*/

    /**
     * Функция изменения активации пользователя при подтверждении
     */
    /*public function confirmEmail() {
        $this->verified = true;
        $this->token = null;

        $this->save();
    }*/

    /**
     * Отправка уведомления об изменении пароля.
     *
     * @param  string  $token
     * @return void
     */
    /*public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }

    public function roles()
    {
        return $this->belongsToMany('App\Role', 'role_user', 'user_id', 'role_id');
    }**/
}
